var BIBLIOTECA_DEVOLUTIVAS={
  E1_INCONSISTENTE:{titulo:'Não apareceu um padrão único hoje',modo_curto:'Hoje não apareceu um padrão dominante claro.',modo_expandido:'As respostas ficaram distribuídas entre diferentes áreas.',acao_pratica:'Pode ajudar observar o que mais chamou sua atenção hoje.'},
  E2_ZERO:{titulo:'Hoje não apareceu cansaço',modo_curto:'Hoje você não percebeu cansaço no seu registro.',modo_expandido:'Nem sempre não perceber cansaço significa que ele não existe. Às vezes a gente se acostuma e deixa de notar.',acao_pratica:'Pode ajudar parar um momento e observar bem sua respiração e seu corpo.'},
  E3_LEVE_UNIFORME:{titulo:'Tudo está mais lento',modo_curto:'Hoje tudo parece estar mais lento.',modo_expandido:'As coisas estão acontecendo, porém mais devagar do que o normal.',acao_pratica:'Pode ajudar diminuir o ritmo e fazer menos tarefas hoje.'},
  E3_LEVE_DIFUSO:{titulo:'Funcionamento leve e irregular',modo_curto:'Hoje as coisas funcionam, mas sem muita consistência.',modo_expandido:'Você consegue fazer, mas com variação ao longo do dia. Em alguns momentos flui, em outros não.',acao_pratica:'Pode ajudar escolher poucas tarefas e manter um ritmo mais constante.'},
  E4_MEDIA_UNIFORME:{titulo:'Tudo exige esforço',modo_curto:'Hoje tudo exige esforço para acontecer, até nas coisas simples.',modo_expandido:'Hoje tudo exige esforço para acontecer. Mesmo as coisas simples precisam de mais energia do que o normal.',acao_pratica:'Pode ajudar manter apenas o necessário e evitar começar coisas novas.'},
  CARGA_ALTA_UNIFORME:{titulo:'No limite',modo_curto:'Parece que hoje você está no seu limite.',modo_expandido:'Tudo está exigindo muito de você, mas você ainda está conseguindo dar conta. Isso mantém o dia andando, mas com desgaste alto.',acao_pratica:'Pode ajudar diminuir o ritmo hoje e não assumir novas tarefas. Vale fazer uma pausa antes de seguir.'},
  SATURACAO_MAXIMA:{titulo:'Você está saturado',modo_curto:'Hoje tudo está no máximo. Não dá para sustentar assim.',modo_expandido:'Seu corpo, sua mente e sua ação estão todos no limite ao mesmo tempo. Não é só esforço alto. Tudo está no máximo ao mesmo tempo. Continuar assim tende a aumentar o desgaste.',acao_pratica:'Pode ajudar parar o que não for essencial, reduzir estímulos e buscar um ambiente mais calmo.'},
  SOBRECARGA_EMOCIONAL:{titulo:'Emoção interferindo',modo_curto:'O que você está sentindo agora está interferindo no seu dia.',modo_expandido:'O que você está sentindo começa a influenciar suas decisões. Você muda o que faz ao longo do dia sem perceber.',acao_pratica:'Foque apenas no essencial e evite o que te desgasta hoje. Um ambiente mais silencioso pode ajudar a recuperar o fôlego.'},
  SOBRECARGA_ORGANIZACIONAL:{titulo:'Organização difícil',modo_curto:'Hoje está difícil organizar suas tarefas.',modo_expandido:'Você tem várias coisas para fazer, mas não consegue definir uma ordem. Isso faz você começar várias e terminar poucas.',acao_pratica:'Pode ajudar escolher uma tarefa para fazer e ignorar o que não for importante agora.'},
  ORGANIZAR_DOMINANTE:{titulo:'Organização puxando o dia',modo_curto:'Você está tentando organizar tudo para dar conta do dia.',modo_expandido:'Sua atenção está muito voltada para organizar, planejar ou controlar. Isso ajuda em parte, mas pode travar a ação.',acao_pratica:'Pode ajudar parar de organizar por um momento e iniciar uma tarefa simples.'},
  SOBRECARGA_DE_ACAO:{titulo:'Fazer está difícil',modo_curto:'Hoje está mais difícil fazer as coisas acontecerem.',modo_expandido:'Você consegue fazer, mas tudo exige mais esforço do que deveria. Isso reduz o ritmo e aumenta o cansaço ao longo do dia.',acao_pratica:'Dê um descanso à sua lista de tarefas e faça apenas o que não pode esperar.'},
  BAIXO_SENTIDO_CRITICO:{titulo:'Sem sentido suficiente para sustentar',modo_curto:'O que você está fazendo não está sustentando seu esforço.',modo_expandido:'Mesmo com esforço alto, falta conexão com o que você está fazendo. Isso aumenta desgaste e reduz sustentação ao longo do tempo.',acao_pratica:'Hoje vale reduzir o que não faz sentido e focar apenas no que vale.'},
  A23_SENTIDO_ALTO:{titulo:'Você continua porque acredita',modo_curto:'O dia está mais exigente, mas você continua porque isso ainda faz sentido para você.',modo_expandido:'Você continua porque isso importa para você. Mesmo assim, o cansaço vai se acumulando aos poucos.',acao_pratica:'Diminua o ritmo hoje e pare por um tempo para se recompor.'},
  A21_MENTE_EXAUSTA:{titulo:'Pensamento sobrecarregado',modo_curto:'Agora está difícil organizar o pensamento.',modo_expandido:'Sua capacidade de analisar e decidir está baixa. Quanto mais você tenta pensar, mais confuso fica.',acao_pratica:'Pode ajudar adiar decisões que não sejam necessárias agora. Vale parar um momento antes de continuar.'},
  FALSO_FUNCIONAL:{titulo:'Funcionando com esforço',modo_curto:'Parece que está tudo bem, mas está exigindo mais do que parece.',modo_expandido:'Por fora você segue funcionando, mas tudo está exigindo mais do que parece. Isso vai se acumulando sem chamar atenção.',acao_pratica:'Diminua um pouco seu ritmo. Vá mais devagar e inclua pequenas pausas. Isso ajuda a não esgotar sua energia.'},
  M17_RUMINACAO:{titulo:'Pensamento repetitivo',modo_curto:'Os pensamentos estão repetitivos.',modo_expandido:'Você fica voltando nas mesmas ideias e possibilidades, mas não sai disso. O dia não avança porque tudo fica sendo revisado.',acao_pratica:'Pode ajudar escolher uma decisão simples e executar sem revisar. Apenas fazer.'},
  ATROPELO_SEM_ORDEM:{titulo:'Sem ordem',modo_curto:'Está tudo acontecendo ao mesmo tempo, sem muita ordem.',modo_expandido:'Está tudo acontecendo ao mesmo tempo, de forma aleatória.',acao_pratica:'Pode ajudar parar o que está difícil agora e retomar apenas uma tarefa.'},
  SENTIR_DOMINANTE:{titulo:'Conflito interno',modo_curto:'Hoje o que você está sentindo está pesando mais do que o normal.',modo_expandido:'O que você está sentindo está influenciando suas decisões e ações. Isso pode mudar o rumo do dia sem você perceber.',acao_pratica:'Antes de tomar decisão, pode ajudar parar um instante e perceber como você está se sentindo.'},
  PROPOSITO_DOMINANTE:{titulo:'O sentido está puxando você',modo_curto:'Mesmo com dificuldade, você continua porque isso importa.',modo_expandido:'O que você faz tem peso para você. Isso sustenta o movimento, mesmo com esforço.',acao_pratica:'Mantenha o ritmo, mas sem ultrapassar seus limites.'},
  M16_CONFLITO:{titulo:'Dificuldade de iniciar',modo_curto:'Você sabe o que fazer, mas não consegue começar.',modo_expandido:'Você entende o que precisa ser feito, mas não consegue iniciar. A tarefa fica parada mesmo sendo óbvia e simples.',acao_pratica:'Tente começar por algo bem simples. Dar o primeiro passo já é uma vitória hoje.'},
  L7_SEM_SENTIDO:{titulo:'Você está fazendo, mas sem conexão',modo_curto:'Você está fazendo as tarefas, mas sem muita conexão. Elas começam a parecer automáticas.',modo_expandido:'Você está fazendo as tarefas, mas sem se envolver. Isso vai cansando aos poucos, mesmo sem esforço alto.',acao_pratica:'Escolha uma tarefa e tente se reconectar com o porquê ela importa para você.'},
  L8_CORPO_BAIXO:{titulo:'Seu corpo não acompanha',modo_curto:'Sua mente quer seguir, mas seu corpo não acompanha. Você até se organiza, mas com pouca energia.',modo_expandido:'Você consegue pensar e se organizar, mas na hora de agir falta energia. Isso faz com que tudo custe mais do que deveria ao longo do dia.',acao_pratica:'Deite-se mais cedo hoje e tente relaxar para dormir melhor. Agora o mais importante é reduzir o esforço físico.'},
  LEVE_COM_MENTE_BAIXA:{titulo:'Pensamento lento',modo_curto:'Hoje está difícil pensar com clareza.',modo_expandido:'Seu pensamento está mais lento. Isso dificulta organizar e decidir o que fazer.',acao_pratica:'Pode ajudar escolher fazer tarefas simples hoje.'},
  LEVE_COM_ACAO_BAIXA:{titulo:'Dificuldade de agir',modo_curto:'Está difícil fazer qualquer coisa.',modo_expandido:'Você sabe o que precisa fazer, mas não transforma isso em ação de verdade.',acao_pratica:'Escolha algo fácil para começar e foque no agora, sem se preocupar com outras tarefas.'},
  LEVE_COM_PROPOSITO_BAIXO:{titulo:'Pouca conexão com o que faz',modo_curto:'Hoje está leve, mas sem muito sentido.',modo_expandido:'As coisas acontecem, mas sem envolvimento. Isso pode levar a desengajamento ao longo do tempo.',acao_pratica:'Escolha algo pequeno que faça sentido para você hoje.'},
  C24_COLAPSO:{titulo:'Está muito difícil agora',modo_curto:'Agora o que está sendo exigido está além do que você consegue dar conta.',modo_expandido:'Seu corpo e sua mente estão no limite. Continuar nesse ritmo vai aumentar o desgaste.',acao_pratica:'Hoje vale reduzir exigências e proteger sua energia.'}
};

var MAPA_MOTOR_BIBLIOTECA={
  inconsistencia_tecnica:'E1_INCONSISTENTE',
  ausencia_de_sinal:'E2_ZERO',
  carga_leve_uniforme:'E3_LEVE_UNIFORME',
  carga_difusa:'E4_MEDIA_UNIFORME',
  carga_alta_uniforme:'CARGA_ALTA_UNIFORME',
  saturacao_maxima:'SATURACAO_MAXIMA',
  colapso_global:'C24_COLAPSO',
  sobrecarga_emocional:'SOBRECARGA_EMOCIONAL',
  sobrecarga_organizacional:'SOBRECARGA_ORGANIZACIONAL',
  sobrecarga_de_acao:'SOBRECARGA_DE_ACAO',
  baixo_sentido:'BAIXO_SENTIDO_CRITICO',
  sobrecarga_com_sentido:'A23_SENTIDO_ALTO',
  limite_funcional:'A21_MENTE_EXAUSTA',
  falso_funcional:'FALSO_FUNCIONAL',
  ruminacao_sem_acao:'M17_RUMINACAO',
  atropelo_sem_ordem:'ATROPELO_SEM_ORDEM',
  sentir_dominante:'SENTIR_DOMINANTE',
  organizar_dominante:'ORGANIZAR_DOMINANTE',
  agir_dominante:'M16_CONFLITO',
  proposito_dominante:'PROPOSITO_DOMINANTE',
  leve_difuso:'E3_LEVE_DIFUSO',
  leve_sem_sentido:'L7_SEM_SENTIDO',
  leve_com_corpo_baixo:'L8_CORPO_BAIXO',
  leve_com_mente_baixa:'LEVE_COM_MENTE_BAIXA',
  leve_com_acao_baixa:'LEVE_COM_ACAO_BAIXA',
  leve_com_proposito_baixo:'LEVE_COM_PROPOSITO_BAIXO'
};
